### PR TITLE
env: Force a separate Firefox profile

### PR DESCRIPTION
**Pull request by hoshinolina**
Otherwise Firefox launched in the guest will concurrently access the host profile, corrupting it. We can make it not do that by implementing locks, which would fix the corruption but would still break the browser in the guest. So let's explicitly set a muvm-private Firefox profile.

### CODE REVIEW

**Comment by teohhanhui** [comment]
Firefox communicates over d-bus to connect to an existing instance, right?

I think perhaps the right way to go is to forward that? Which IIUC will fix other things like some desktop integration too...

**Comment by WhatAmISupposedToPutHere** [comment]
Dbus forwarding would be nice to have, but it is more complicated than it looks (there is fd passing involved), and you would need to have a "dbus firewall", as we will want certain objects to be separate between host and guest. I would say it is a bit too much rn, and the solution above works.

**Review by slp — APPROVED** [review]
LGTM

**Comment by shaoyanji** [comment]
i was wondering about this. i run a nix home-manager firefox-esr to port my stuff over and each build corrupts the profile.ini file. my fix: to add a pre and posthook to backup and replace to keep the previous profile.ini to just keep the native firefox to work. curious if this works for the firefox-esr

**Comment by asahilina** [comment]
That sounds like a different issue, I think? It's not profile.ini that gets corrupted, it's the actual profile databases (the ones that go quickly are cookies and places (history)). This happens because the VM does not share locks with the host (yet), so the normal locking that Firefox does on the profile does not work. If you are running multiple Firefox instances without a filesystem or OS layer that makes locks not work across them, they should not be able to launch concurrently on the same profile.

The environment variable probably works for all versions of Firefox though, if you want to try it.

**Comment by Shados** [comment]
> and you would need to have a "dbus firewall", as we will want certain objects to be separate between host and guest

Worth noting that xdg-dbus-proxy does exist, motivated by similar goals within flatpak.

**Comment by orowith2os** [comment]
> Worth noting that xdg-dbus-proxy does exist, motivated by similar goals within flatpak.

I would also like to mention that supporting dbus, and otherwise integrating better with other sockets and APIs from the host, would be very useful in running x86 Flatpak apps seamlessly under Apple Silicon.

With x86 apps needing 4KB pages, they'd crash immediately, even if you had a binfmt handler. You could fix this by using muvm, but without integrating with more than just GPU accel, portals and other APIs would fall apart immediately. Would be nice to look at exporting an x86 binfmt handler that runs inside of muvm; I know muvm already provides one, but I haven't checked if this is exposed to the host system at all.

**Comment by waltmck** [comment]
> Dbus forwarding would be nice to have, but it is more complicated than it looks (there is fd passing involved), and you would need to have a "dbus firewall", as we will want certain objects to be separate between host and guest. I would say it is a bit too much rn, and the solution above works.

What objects would you want to be separate between the host and guest?

I know that some people use virtual machines to get isolation/containerization guarantees, but in my opinion these goals can be achieved more elegantly (most of the time) using native kernel features like `chroot` environments, network namespaces, capabilities, etc.

Speaking for myself, I really only need `muvm` in order to run FEX on a 16K machine. I don't need any containerization and I don't need any isolation---on the contrary, the lack of `dbus` services breaks many common apps that I would want to use (such as Slack). It would be great if there were a mode that aimed to provide maximum out-of-the-box integration with the host OS for those who don't care about isolation. A good start might be to pass environment variables and forward every socket in `/run`.

**Pull request merged**
